
    create table schlarb.schlarb_user (
       id int4 generated by default as identity,
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    )
